# Generated by Django 6.0.1 on 2026-06-24 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SincronizacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sync_etl', 'Sincronização ETL'), ('import', 'Importação manual'), ('mapping', 'Aplicação de mappings'), ('restore', 'Restauro de dados')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('partial', 'Parcial (com erros)'), ('failed', 'Falhou')], db_index=True, max_length=10)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('duracao_segundos', models.FloatField(blank=True, null=True)),
                ('resumo', models.JSONField(blank=True, default=dict, help_text='JSON com contagens: criados, atualizados, erros por tabela')),
                ('detalhes', models.TextField(blank=True, help_text='Log detalhado da operação')),
                ('executado_por', models.CharField(blank=True, help_text='Utilizador ou sistema que executou', max_length=100)),
            ],
            options={
                'verbose_name': 'Log de Sincronização',
                'verbose_name_plural': 'Logs de Sincronização',
                'db_table': 'sincronizacao_log',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
