# Generated by Django 6.0.1 on 2026-05-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='localidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='formador',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='formador',
            name='descricao_postal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='formando',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='formando',
            name='localidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='localidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalformador',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalformador',
            name='descricao_postal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='localidade',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
