# Generated by Django 6.0.1 on 2026-05-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_alter_empresa_codigo_postal_alter_empresa_localidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=500, verbose_name='Nome do Curso'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=500, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='formador',
            name='nome',
            field=models.CharField(max_length=500, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='formando',
            name='nome',
            field=models.CharField(max_length=500, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalcurso',
            name='nome',
            field=models.CharField(max_length=500, verbose_name='Nome do Curso'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='nome',
            field=models.CharField(max_length=500, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='historicalformador',
            name='nome',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='nome',
            field=models.CharField(max_length=500, verbose_name='Nome'),
        ),
    ]
