# Generated by Django 6.0.1 on 2026-05-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_alter_curso_nome_alter_empresa_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formador',
            name='nome',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalformador',
            name='nome',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nome'),
        ),
    ]
