# Generated by Django 6.0.1 on 2026-05-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_alter_formador_nome_alter_historicalformador_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='referencia',
            field=models.CharField(max_length=255, unique=True, verbose_name='Refº da Ação'),
        ),
        migrations.AlterField(
            model_name='formador',
            name='telefone1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='formador',
            name='telefone2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalacao',
            name='referencia',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Refº da Ação'),
        ),
        migrations.AlterField(
            model_name='historicalformador',
            name='telefone1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalformador',
            name='telefone2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
