# Generated by Django 6.0.1 on 2026-05-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0005_alter_acao_referencia_alter_formador_telefone1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='historicalempresa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='historicalempresa',
            name='telefone',
        ),
    ]
