# Generated by Django 6.0.1 on 2026-05-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0006_remove_empresa_email_remove_empresa_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='referencia',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Refº da Ação'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='formador',
            name='nome',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='formando',
            name='nome',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='nome',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='nome',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalinscricao',
            name='comercial',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalinscricao',
            name='numero_certificado',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Nº Certificado'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='comercial',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='numero_certificado',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Nº Certificado'),
        ),
    ]
