# Generated by Django 6.0.1 on 2026-05-06 10:33

import django.db.models.deletion
import entidades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0007_alter_acao_referencia_alter_empresa_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='ano',
            field=models.CharField(blank=True, db_column='ano_acao', max_length=4, verbose_name='Ano Ação'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='data_fim',
            field=models.CharField(blank=True, db_column='data_fim_turma', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acao',
            name='data_inicio',
            field=models.CharField(blank=True, db_column='data_inicio_turma', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acao',
            name='formador',
            field=models.ForeignKey(blank=True, db_column='id_formador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes', to='entidades.formador', verbose_name='Formador'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='id',
            field=models.BigAutoField(db_column='id_acao', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='acao',
            name='local',
            field=models.CharField(blank=True, db_column='local_de_formacao', max_length=255, verbose_name='Local de Formação'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='referencia',
            field=models.CharField(db_column='refo_da_acao', db_index=True, max_length=255, unique=True, verbose_name='Refº da Ação'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='codigo_postal',
            field=models.CharField(blank=True, db_column='codigo_postal', max_length=50),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.BigAutoField(db_column='id_empresa', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='localidade',
            field=models.CharField(blank=True, db_column='localidade', max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='morada',
            field=models.CharField(blank=True, db_column='morada', max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nif',
            field=models.CharField(db_column='nif_empresa', max_length=9, unique=True, validators=[entidades.models.validar_nif], verbose_name='NIF Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(db_column='empresa', db_index=True, max_length=500, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='formador',
            name='codigo',
            field=models.CharField(blank=True, db_column='cod', max_length=20, verbose_name='Cód.'),
        ),
        migrations.AlterField(
            model_name='formador',
            name='codigo_postal',
            field=models.CharField(blank=True, db_column='codigo_postal', max_length=50),
        ),
        migrations.AlterField(
            model_name='formador',
            name='data_nascimento',
            field=models.CharField(blank=True, db_column='data_nascimento', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formador',
            name='descricao_postal',
            field=models.CharField(blank=True, db_column='descricao_postal', max_length=255),
        ),
        migrations.AlterField(
            model_name='formador',
            name='email1',
            field=models.EmailField(blank=True, db_column='email_1', max_length=254),
        ),
        migrations.AlterField(
            model_name='formador',
            name='email2',
            field=models.EmailField(blank=True, db_column='email_2', max_length=254),
        ),
        migrations.AlterField(
            model_name='formador',
            name='id',
            field=models.BigAutoField(db_column='id_formador', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formador',
            name='morada',
            field=models.CharField(blank=True, db_column='morada', max_length=255),
        ),
        migrations.AlterField(
            model_name='formador',
            name='nome',
            field=models.CharField(db_column='formador', db_index=True, max_length=255, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='formador',
            name='telefone1',
            field=models.CharField(blank=True, db_column='telefone_1', max_length=100),
        ),
        migrations.AlterField(
            model_name='formador',
            name='telefone2',
            field=models.CharField(blank=True, db_column='telefone_2', max_length=100),
        ),
        migrations.AlterField(
            model_name='formando',
            name='codigo_postal',
            field=models.CharField(blank=True, db_column='codigo_postal', max_length=50),
        ),
        migrations.AlterField(
            model_name='formando',
            name='data_nascimento',
            field=models.CharField(blank=True, db_column='data_nascimento', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formando',
            name='email',
            field=models.EmailField(blank=True, db_column='email', max_length=254),
        ),
        migrations.AlterField(
            model_name='formando',
            name='id',
            field=models.BigAutoField(db_column='id_formando', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formando',
            name='localidade',
            field=models.CharField(blank=True, db_column='descricao_postal', max_length=255),
        ),
        migrations.AlterField(
            model_name='formando',
            name='morada',
            field=models.CharField(blank=True, db_column='morada', max_length=255),
        ),
        migrations.AlterField(
            model_name='formando',
            name='naturalidade',
            field=models.CharField(blank=True, db_column='naturalidade', max_length=100),
        ),
        migrations.AlterField(
            model_name='formando',
            name='nif',
            field=models.CharField(blank=True, db_column='nif_formando', max_length=9, null=True, unique=True, validators=[entidades.models.validar_nif], verbose_name='NIF Formando'),
        ),
        migrations.AlterField(
            model_name='formando',
            name='nome',
            field=models.CharField(db_column='formando', db_index=True, max_length=500, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='formando',
            name='numero_identificacao',
            field=models.CharField(blank=True, db_column='no_identificacao', max_length=30),
        ),
        migrations.AlterField(
            model_name='formando',
            name='telefone',
            field=models.CharField(blank=True, db_column='telefone', max_length=20),
        ),
        migrations.AlterField(
            model_name='formando',
            name='tipo_identificacao',
            field=models.CharField(blank=True, db_column='tipo_identificacao', max_length=50),
        ),
        migrations.AlterField(
            model_name='formando',
            name='validade_identificacao',
            field=models.CharField(blank=True, db_column='validade_identificacao', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalacao',
            name='ano',
            field=models.CharField(blank=True, db_column='ano_acao', max_length=4, verbose_name='Ano Ação'),
        ),
        migrations.AlterField(
            model_name='historicalacao',
            name='data_fim',
            field=models.CharField(blank=True, db_column='data_fim_turma', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalacao',
            name='data_inicio',
            field=models.CharField(blank=True, db_column='data_inicio_turma', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalacao',
            name='formador',
            field=models.ForeignKey(blank=True, db_column='id_formador', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entidades.formador', verbose_name='Formador'),
        ),
        migrations.AlterField(
            model_name='historicalacao',
            name='id',
            field=models.BigIntegerField(blank=True, db_column='id_acao', db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalacao',
            name='local',
            field=models.CharField(blank=True, db_column='local_de_formacao', max_length=255, verbose_name='Local de Formação'),
        ),
        migrations.AlterField(
            model_name='historicalacao',
            name='referencia',
            field=models.CharField(db_column='refo_da_acao', db_index=True, max_length=255, verbose_name='Refº da Ação'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='codigo_postal',
            field=models.CharField(blank=True, db_column='codigo_postal', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='id',
            field=models.BigIntegerField(blank=True, db_column='id_empresa', db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='localidade',
            field=models.CharField(blank=True, db_column='localidade', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='morada',
            field=models.CharField(blank=True, db_column='morada', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='nif',
            field=models.CharField(db_column='nif_empresa', db_index=True, max_length=9, validators=[entidades.models.validar_nif], verbose_name='NIF Empresa'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='nome',
            field=models.CharField(db_column='empresa', db_index=True, max_length=500, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='historicalformador',
            name='codigo',
            field=models.CharField(blank=True, db_column='cod', max_length=20, verbose_name='Cód.'),
        ),
        migrations.AlterField(
            model_name='historicalformador',
            name='codigo_postal',
            field=models.CharField(blank=True, db_column='codigo_postal', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalformador',
            name='data_nascimento',
            field=models.CharField(blank=True, db_column='data_nascimento', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformador',
            name='descricao_postal',
            field=models.CharField(blank=True, db_column='descricao_postal', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalformador',
            name='email1',
            field=models.EmailField(blank=True, db_column='email_1', max_length=254),
        ),
        migrations.AlterField(
            model_name='historicalformador',
            name='email2',
            field=models.EmailField(blank=True, db_column='email_2', max_length=254),
        ),
        migrations.AlterField(
            model_name='historicalformador',
            name='id',
            field=models.BigIntegerField(blank=True, db_column='id_formador', db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalformador',
            name='morada',
            field=models.CharField(blank=True, db_column='morada', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalformador',
            name='nome',
            field=models.CharField(db_column='formador', db_index=True, max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalformador',
            name='telefone1',
            field=models.CharField(blank=True, db_column='telefone_1', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalformador',
            name='telefone2',
            field=models.CharField(blank=True, db_column='telefone_2', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='codigo_postal',
            field=models.CharField(blank=True, db_column='codigo_postal', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='data_nascimento',
            field=models.CharField(blank=True, db_column='data_nascimento', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='email',
            field=models.EmailField(blank=True, db_column='email', max_length=254),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='id',
            field=models.BigIntegerField(blank=True, db_column='id_formando', db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='localidade',
            field=models.CharField(blank=True, db_column='descricao_postal', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='morada',
            field=models.CharField(blank=True, db_column='morada', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='naturalidade',
            field=models.CharField(blank=True, db_column='naturalidade', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='nif',
            field=models.CharField(blank=True, db_column='nif_formando', db_index=True, max_length=9, null=True, validators=[entidades.models.validar_nif], verbose_name='NIF Formando'),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='nome',
            field=models.CharField(db_column='formando', db_index=True, max_length=500, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='numero_identificacao',
            field=models.CharField(blank=True, db_column='no_identificacao', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='telefone',
            field=models.CharField(blank=True, db_column='telefone', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='tipo_identificacao',
            field=models.CharField(blank=True, db_column='tipo_identificacao', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='validade_identificacao',
            field=models.CharField(blank=True, db_column='validade_identificacao', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinscricao',
            name='acao',
            field=models.ForeignKey(blank=True, db_column='id_acao', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entidades.acao', verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='historicalinscricao',
            name='comercial',
            field=models.CharField(blank=True, db_column='comercial', db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalinscricao',
            name='data_estado_profissional',
            field=models.CharField(blank=True, db_column='data_estado_profissional', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinscricao',
            name='data_inscricao',
            field=models.CharField(blank=True, db_column='data_inscricao', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinscricao',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entidades.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='historicalinscricao',
            name='estado_pagamento',
            field=models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], db_column='estado_pagamento', default='Pendente', max_length=50, verbose_name='Estado Pagamento'),
        ),
        migrations.AlterField(
            model_name='historicalinscricao',
            name='estado_profissional',
            field=models.CharField(choices=[('Certificado', 'Certificado'), ('Desistente', 'Desistente'), ('Falta doc', 'Falta Documentação'), ('Inscrito', 'Inscrito')], db_column='estado_profissional', default='Inscrito', max_length=50, verbose_name='Estado Profissional'),
        ),
        migrations.AlterField(
            model_name='historicalinscricao',
            name='formando',
            field=models.ForeignKey(blank=True, db_column='id_formando', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entidades.formando', verbose_name='Formando'),
        ),
        migrations.AlterField(
            model_name='historicalinscricao',
            name='id',
            field=models.BigIntegerField(blank=True, db_column='id_inscricao', db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalinscricao',
            name='numero_certificado',
            field=models.CharField(blank=True, db_column='no_de_certificado', db_index=True, max_length=200, verbose_name='Nº Certificado'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='acao',
            field=models.ForeignKey(db_column='id_acao', on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='entidades.acao', verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='comercial',
            field=models.CharField(blank=True, db_column='comercial', db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='data_estado_profissional',
            field=models.CharField(blank=True, db_column='data_estado_profissional', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='data_inscricao',
            field=models.CharField(blank=True, db_column='data_inscricao', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes', to='entidades.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='estado_pagamento',
            field=models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], db_column='estado_pagamento', default='Pendente', max_length=50, verbose_name='Estado Pagamento'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='estado_profissional',
            field=models.CharField(choices=[('Certificado', 'Certificado'), ('Desistente', 'Desistente'), ('Falta doc', 'Falta Documentação'), ('Inscrito', 'Inscrito')], db_column='estado_profissional', default='Inscrito', max_length=50, verbose_name='Estado Profissional'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='formando',
            field=models.ForeignKey(db_column='id_formando', on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='entidades.formando', verbose_name='Formando'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='id',
            field=models.BigAutoField(db_column='id_inscricao', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='numero_certificado',
            field=models.CharField(blank=True, db_column='no_de_certificado', db_index=True, max_length=200, verbose_name='Nº Certificado'),
        ),
        migrations.AlterModelTable(
            name='acao',
            table='acoes',
        ),
        migrations.AlterModelTable(
            name='curso',
            table='cursos',
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='empresas',
        ),
        migrations.AlterModelTable(
            name='formador',
            table='formadores',
        ),
        migrations.AlterModelTable(
            name='formando',
            table='formandos',
        ),
        migrations.AlterModelTable(
            name='inscricao',
            table='inscricoes',
        ),
    ]
