# Generated by Django 6.0.1 on 2026-06-24 16:54

import django.db.models.deletion
import entidades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0015_normalizar_estado_inscrito'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inscricao',
            name='idx_insc_fo_id',
        ),
        migrations.RemoveIndex(
            model_name='inscricao',
            name='idx_insc_est_acao',
        ),
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='acao',
            name='id_etl',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID Fonte ETL'),
        ),
        migrations.AddField(
            model_name='curso',
            name='id_etl',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID Fonte ETL'),
        ),
        migrations.AddField(
            model_name='formador',
            name='id_etl',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID Fonte ETL'),
        ),
        migrations.AddField(
            model_name='formando',
            name='id_etl',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID Fonte ETL'),
        ),
        migrations.AddField(
            model_name='historicalacao',
            name='id_etl',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID Fonte ETL'),
        ),
        migrations.AddField(
            model_name='historicalcurso',
            name='id_etl',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID Fonte ETL'),
        ),
        migrations.AddField(
            model_name='historicalformador',
            name='id_etl',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID Fonte ETL'),
        ),
        migrations.AddField(
            model_name='historicalformando',
            name='id_etl',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID Fonte ETL'),
        ),
        migrations.AddField(
            model_name='historicalinscricao',
            name='id_etl',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID Fonte ETL'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='id_etl',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID Fonte ETL'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='ano',
            field=models.CharField(blank=True, db_column='ano_acao', db_index=True, max_length=4, verbose_name='Ano Ação'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='referencia',
            field=models.CharField(db_column='refo_da_acao', db_index=True, max_length=255, verbose_name='Refº da Ação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='area_codigo',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Cód. Área'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Código Curso'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nif',
            field=models.CharField(db_column='nif_empresa', max_length=9, validators=[entidades.models.validar_nif], verbose_name='NIF Empresa'),
        ),
        migrations.AlterField(
            model_name='formador',
            name='email1',
            field=models.EmailField(blank=True, db_column='email_1', db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='formador',
            name='nome',
            field=models.CharField(db_column='formador', db_index=True, max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='formando',
            name='email',
            field=models.EmailField(blank=True, db_column='email', db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='formando',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formandos', to='entidades.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='formando',
            name='nif',
            field=models.CharField(blank=True, db_column='nif_formando', max_length=9, null=True, validators=[entidades.models.validar_nif], verbose_name='NIF Formando'),
        ),
        migrations.AlterField(
            model_name='historicalacao',
            name='ano',
            field=models.CharField(blank=True, db_column='ano_acao', db_index=True, max_length=4, verbose_name='Ano Ação'),
        ),
        migrations.AlterField(
            model_name='historicalcurso',
            name='area_codigo',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Cód. Área'),
        ),
        migrations.AlterField(
            model_name='historicalcurso',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Código Curso'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='nif',
            field=models.CharField(db_column='nif_empresa', max_length=9, validators=[entidades.models.validar_nif], verbose_name='NIF Empresa'),
        ),
        migrations.AlterField(
            model_name='historicalformador',
            name='email1',
            field=models.EmailField(blank=True, db_column='email_1', db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='email',
            field=models.EmailField(blank=True, db_column='email', db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entidades.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='historicalformando',
            name='nif',
            field=models.CharField(blank=True, db_column='nif_formando', max_length=9, null=True, validators=[entidades.models.validar_nif], verbose_name='NIF Formando'),
        ),
        migrations.AlterField(
            model_name='historicalinscricao',
            name='estado_pagamento',
            field=models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], db_column='estado_pagamento', db_index=True, default='Pendente', max_length=50, verbose_name='Estado Pagamento'),
        ),
        migrations.AlterField(
            model_name='historicalinscricao',
            name='estado_profissional',
            field=models.CharField(choices=[('Certificado', 'Certificado'), ('Desistente', 'Desistente'), ('Pendente', 'Pendente')], db_column='estado_profissional', db_index=True, default='Pendente', max_length=50, verbose_name='Estado Profissional'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='estado_pagamento',
            field=models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], db_column='estado_pagamento', db_index=True, default='Pendente', max_length=50, verbose_name='Estado Pagamento'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='estado_profissional',
            field=models.CharField(choices=[('Certificado', 'Certificado'), ('Desistente', 'Desistente'), ('Pendente', 'Pendente')], db_column='estado_profissional', db_index=True, default='Pendente', max_length=50, verbose_name='Estado Profissional'),
        ),
        migrations.AddConstraint(
            model_name='acao',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('referencia',), name='unique_ref_acao_ativo', violation_error_message='Já existe uma ação ativa com esta referência.'),
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('codigo',), name='unique_codigo_curso_ativo', violation_error_message='Já existe um curso ativo com este código.'),
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('nif',), name='unique_nif_empresa_ativo', violation_error_message='Já existe uma empresa ativa com este NIF.'),
        ),
        migrations.AddConstraint(
            model_name='formador',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('nome',), name='unique_nome_formador_ativo', violation_error_message='Já existe um formador ativo com este nome.'),
        ),
        migrations.AddConstraint(
            model_name='formando',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('nif',), name='unique_nif_formando_ativo', violation_error_message='Já existe um formando ativo com este NIF.'),
        ),
        migrations.AddConstraint(
            model_name='inscricao',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('formando', 'acao'), name='unique_inscricao_ativo', violation_error_message='Este formando já está inscrito nesta ação.'),
        ),
    ]
