# Generated by Django 6.0.1 on 2026-05-06 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0008_alter_acao_ano_alter_acao_data_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ML_Previsao_Churn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidade_desistencia', models.FloatField(help_text='Valor de 0.0 a 100.0', verbose_name='Probabilidade de Desistência (%)')),
                ('principais_fatores', models.TextField(blank=True, verbose_name='Principais Fatores')),
                ('data_previsao', models.DateTimeField(auto_now=True, verbose_name='Data da Previsão')),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='previsao_churn', to='entidades.inscricao', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Previsão de Desistência',
                'verbose_name_plural': 'Previsões de Desistência',
                'ordering': ['-probabilidade_desistencia'],
            },
        ),
        migrations.CreateModel(
            name='ML_Recomendacao_Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_confianca', models.FloatField(help_text='Valor de 0.0 a 100.0', verbose_name='Score de Confiança (%)')),
                ('data_recomendacao', models.DateTimeField(auto_now=True, verbose_name='Data da Recomendação')),
                ('curso_sugerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.curso', verbose_name='Curso Sugerido')),
                ('formando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_ml', to='entidades.formando', verbose_name='Formando')),
            ],
            options={
                'verbose_name': 'Recomendação de Curso',
                'verbose_name_plural': 'Recomendações de Cursos',
                'ordering': ['-score_confianca'],
            },
        ),
    ]
