# Generated by Django 6.0.1 on 2026-05-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos_previsao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ml_previsao_churn',
            table='previsoes_churn',
        ),
        migrations.AlterModelTable(
            name='ml_recomendacao_curso',
            table='recomendacoes_cursos',
        ),
    ]
